Do the following in the iris dataset

1.Read the dataset to python environment 2.Do the necessary pre-processing steps 3.Find out which classification model gives the best result (try all the classification algorithms discussed in the session)

1.Read the Dataset into the Python Environment.

In [2]:
import pandas as pd
import numpy as np
# Load the Iris dataset
df = pd.read_excel(r"C:\Users\csaru\Downloads\iris (1).xls")

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [6]:
 #Display the columns
print(df.columns)

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')


In [8]:
#Check for missing values:

missing_values = df.isnull().sum()
print(missing_values)

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64


In [9]:
# Handling missing values (if any)
df.dropna(inplace=True)

In [10]:
missing_values = df.isnull().sum()
print(missing_values)

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64


In [11]:
# Split the dataset into features and labels
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [16]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [17]:
# Display results
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (104, 4)
y_train shape: (104,)
X_test shape: (27, 4)
y_test shape: (27,)


In [21]:

# Scale the features separately for each model
scaler_lr = StandardScaler()
scaler_knn = StandardScaler()
scaler_svm = StandardScaler()
scaler_dt = StandardScaler()
scaler_rf = StandardScaler()


In [22]:
# Logistic Regression
lr = LogisticRegression()
X_train_lr = scaler_lr.fit_transform(X_train)
X_test_lr = scaler_lr.transform(X_test)
lr.fit(X_train_lr, y_train)
lr_pred = lr.predict(X_test_lr)
lr_accuracy = accuracy_score(y_test, lr_pred)
lr_cm = confusion_matrix(y_test, lr_pred)
lr_report = classification_report(y_test, lr_pred)

print("Logistic Regression:")
print("Accuracy:", lr_accuracy)
print("Confusion Matrix:\n", lr_cm)
print("Classification Report:\n", lr_report)


Logistic Regression:
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0  8]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27



In [23]:
# K-Nearest Neighbors
knn = KNeighborsClassifier()
X_train_knn = scaler_knn.fit_transform(X_train)
X_test_knn = scaler_knn.transform(X_test)
knn.fit(X_train_knn, y_train)
knn_pred = knn.predict(X_test_knn)
knn_accuracy = accuracy_score(y_test, knn_pred)
knn_cm = confusion_matrix(y_test, knn_pred)
knn_report = classification_report(y_test, knn_pred)

print("\nK-Nearest Neighbors:")
print("Accuracy:", knn_accuracy)
print("Confusion Matrix:\n", knn_cm)
print("Classification Report:\n", knn_report)



K-Nearest Neighbors:
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0  8]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27



C:\Users\csaru\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [24]:
# Support Vector Machines
svm = SVC()
X_train_svm = scaler_svm.fit_transform(X_train)
X_test_svm = scaler_svm.transform(X_test)
svm.fit(X_train_svm, y_train)
svm_pred = svm.predict(X_test_svm)
svm_accuracy = accuracy_score(y_test, svm_pred)
svm_cm = confusion_matrix(y_test, svm_pred)
svm_report = classification_report(y_test, svm_pred)

In [25]:
print("\nSupport Vector Machines:")
print("Accuracy:", svm_accuracy)
print("Confusion Matrix:\n", svm_cm)
print("Classification Report:\n", svm_report)



Support Vector Machines:
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0  8]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27



In [26]:
# Decision Trees
dt = DecisionTreeClassifier()
X_train_dt = scaler_dt.fit_transform(X_train)
X_test_dt = scaler_dt.transform(X_test)
dt.fit(X_train_dt, y_train)
dt_pred = dt.predict(X_test_dt)
dt_accuracy = accuracy_score(y_test, dt_pred)
dt_cm = confusion_matrix(y_test, dt_pred)
dt_report = classification_report(y_test, dt_pred)

print("\nDecision Trees:")
print("Accuracy:", dt_accuracy)
print("Confusion Matrix:\n", dt_cm)
print("Classification Report:\n", dt_report)



Decision Trees:
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0  8]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27



In [27]:
# Random Forest
rf = RandomForestClassifier()
X_train_rf = scaler_rf.fit_transform(X_train)
X_test_rf = scaler_rf.transform(X_test)
rf.fit(X_train_rf, y_train)
rf_pred = rf.predict(X_test_rf)
rf_accuracy = accuracy_score(y_test, rf_pred)
rf_cm = confusion_matrix(y_test, rf_pred)
rf_report = classification_report(y_test, rf_pred)

print("\nRandom Forest:")
print("Accuracy:", rf_accuracy)
print("Confusion Matrix:\n", rf_cm)
print("Classification Report:\n", rf_report)


Random Forest:
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0  8]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27



In [28]:
# Compare the models and find the best one
accuracies = [lr_accuracy, knn_accuracy, svm_accuracy, dt_accuracy, rf_accuracy]
best_model_idx = np.argmax(accuracies)
best_model = ["Logistic Regression", "K-Nearest Neighbors", "Support Vector Machines", "Decision Trees", "Random Forest"][best_model_idx]

print("\nBest Model:", best_model)


Best Model: Logistic Regression
